name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 (git pull -> docker compose build & up)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CD_EC2_HOST }}
          username: ${{ secrets.CD_EC2_USER }}
          key: ${{ secrets.CD_EC2_SSH_PRIVATE_KEY }}
          port: ${{ secrets.CD_EC2_SSH_PORT }}
          script: |
            set -e
            cd ${{ secrets.CD_EC2_APP_DIR }}

            git fetch --all
            git reset --hard origin/main

            docker compose -f docker-compose-dev.yml --env-file .env.prod down
            docker compose -f docker-compose-dev.yml --env-file .env.prod up -d --build
